# Generated by Django 2.2.7 on 2019-12-27 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20191228_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='liked_projects',
            field=models.ManyToManyField(to='products.Product'),
        ),
    ]
