# Generated by Django 2.2.7 on 2019-12-28 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_profile_liked_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='liked_projects',
        ),
    ]
