# Generated by Django 2.2.7 on 2019-12-28 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_profile_liked_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='liked_projects',
            field=models.ManyToManyField(to='products.Product'),
        ),
    ]
