# Generated by Django 2.2.7 on 2019-12-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_profile_liked_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='liked_projects',
            field=models.ManyToManyField(null=True, to='products.Product'),
        ),
    ]
