# Generated by Django 2.2.7 on 2019-12-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20191228_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='liked_projects',
            field=models.ManyToManyField(blank=True, to='products.Product'),
        ),
    ]
